services:
  chat_db:
    image: postgres:16.3-alpine3.20
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    volumes:
      - chat_db:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - chat_db_network

  migrator:
    build:
      context: .
      dockerfile: migration.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: chat_db
    networks:
      - chat_db_network

  grpc_app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      chat_db_network:

volumes:
  chat_db:
networks:
  chat_db_network:
    driver: bridge