# ./Taskfile.yaml
# See: https://taskfile.dev/api/
version: "3"

vars:
  LOCAL_BIN: "${CURDIR}/bin/"

tasks:
  install-deps:
    - GOBIN={{.LOCAL_BIN}} go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
    - GOBIN={{.LOCAL_BIN}} go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2

  generate:
    - protoc --proto_path api/chat_v1 --go_out=./pkg/chat_v1/
      --go_opt=paths=source_relative --go-grpc_out=./pkg/chat_v1/
      --go-grpc_opt=paths=source_relative api/chat_v1/chat.proto
